### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by hshams522** [DEShawResearch/viparr#1]
Hello! I have installed msys and viparr but when I run 
viparr-convert-charmm -p *.par -t *.rtf myfile
I get the following error
Traceback (most recent call last):
  File "/pathto/viparr-convert-charmm", line 5, in <module>
    import viparr.ffconverter.convert.charmm
  File "/pathto/schrodinger.ve/lib/python3.8/site-packages/viparr/__init__.py", line 3, in <module>
    import msys
  File "/pathto/schrodinger.ve/lib/python3.8/site-packages/msys/__init__.py", line 6, in <module>
    from . import _msys, version
ImportError: cannot import name '_msys' from partially initialized module 'msys' (most likely due to a circular import) (/pathto/schrodinger.ve/lib/python3.8/site-packages/msys/__init__.py)

I've really appreciate your help with this issue.

Best,
Hengi

**Comment by jpessin** [comment]
Hi Hengi,
Clearly something of as viparr try's to import msys.
Can you share abit more about how this was installed?

install context
OS: windows/mac/linux version
python version/source.
how you installed msys: (commands)
how you installed viparr: (commands)

Thanks

**Comment by adamhaber** [comment]
Closing this issue due to inactivity.
